/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Presupuestos;

import Controlador.OperarClientes;
import Controlador.OperarLineaPresMaterial;
import Controlador.OperarLineaPresTrabajo;
import Controlador.OperarMateriales;
import Controlador.OperarPresupuestos;
import Modelo.Cliente;
import Modelo.LineaPresMaterial;
import Modelo.LineaPresTrabajo;
import Modelo.Presupuesto;
import Reportes.ReportePresupuesto;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pfarinamoreno
 */
public class BuscarPresupuesto extends javax.swing.JFrame {

    /**
     * Creates new form ImprimirPresupuesto
     */
    public BuscarPresupuesto() {
        initComponents();
        
        OperarClientes opeClie = new OperarClientes();
        List<Cliente> clientes = opeClie.listarClientes();
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        cbm.addElement("--Seleccionar Cliente--");
        for(int x =0;x<clientes.size();x++){
            String nombre = clientes.get(x).getClienteNombre();
           cbm.addElement(nombre);
        }
        cmb_pre_bus_cli.setModel(cbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_bus_pre_nom = new javax.swing.JTextField();
        cmb_pre_bus_cli = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bus_pre_pre = new javax.swing.JTable();
        btn_bus_pre = new javax.swing.JButton();
        btn_pres_bus_ver = new javax.swing.JButton();
        btn_pre_bus_imp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bus_pre_det = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tot = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_tot_iva = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_iva = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_pre_bus_brr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar Presupuesto");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cliente");

        txt_bus_pre_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bus_pre_nomActionPerformed(evt);
            }
        });

        cmb_pre_bus_cli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_pre_bus_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pre_bus_cliActionPerformed(evt);
            }
        });

        tbl_bus_pre_pre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Presupuesto", "Cliente", "Total sin Iva"
            }
        ));
        jScrollPane1.setViewportView(tbl_bus_pre_pre);

        btn_bus_pre.setText("Buscar Presupuesto");
        btn_bus_pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bus_preActionPerformed(evt);
            }
        });

        btn_pres_bus_ver.setText("Detalles Presupuesto");
        btn_pres_bus_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pres_bus_verActionPerformed(evt);
            }
        });

        btn_pre_bus_imp.setText("Imprimir Presupuesto");
        btn_pre_bus_imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pre_bus_impActionPerformed(evt);
            }
        });

        tbl_bus_pre_det.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tbl_bus_pre_det);

        jLabel4.setText("Detalles del Presupuesto");

        jScrollPane3.setViewportView(txt_tot);

        jScrollPane4.setViewportView(txt_tot_iva);

        jScrollPane5.setViewportView(txt_iva);

        jLabel5.setText("Total:");

        jLabel6.setText("IVA(21%):");

        jLabel7.setText("Total con IVA:");

        btn_pre_bus_brr.setText("Borrar Presupuesto");
        btn_pre_bus_brr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pre_bus_brrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(txt_bus_pre_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_pre_bus_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btn_bus_pre)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_pres_bus_ver)
                                            .addGap(147, 147, 147)
                                            .addComponent(btn_pre_bus_imp)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_pre_bus_brr))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_bus_pre_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_pre_bus_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_bus_pre)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_pres_bus_ver)
                            .addComponent(btn_pre_bus_imp)
                            .addComponent(btn_pre_bus_brr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_pre_bus_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pre_bus_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_pre_bus_cliActionPerformed

    private void txt_bus_pre_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bus_pre_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bus_pre_nomActionPerformed

    private void btn_bus_preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bus_preActionPerformed
        String clienteNombre = (String)cmb_pre_bus_cli.getSelectedItem();
        String concepto = txt_bus_pre_nom.getText();
        
        OperarClientes opeCli = new OperarClientes();
        OperarPresupuestos opePre = new OperarPresupuestos();
        
        int clienteId;
        
        if(clienteNombre.equals("--Seleccionar Cliente--")){
            clienteId = 0;  
        }else{
            Cliente cliente = opeCli.buscarCliente(clienteNombre);
            clienteId =cliente.getClienteId();
        }
        
        List<Presupuesto> presupuestos = opePre.buscarPresupuestos(clienteId, concepto);
        Vector<String> tableHeaders = new Vector <String>();
        Vector tableData = new Vector();
        tableHeaders.add("Presupuesto");
        tableHeaders.add("Cliente");
        tableHeaders.add("Total");
        
        for (Object o : presupuestos){
                Presupuesto presupuesto = (Presupuesto) o;
                Vector<Object> oneRow = new Vector<Object>();

                oneRow.add(presupuesto.getPresupuestoTrabajo());
                oneRow.add(presupuesto.getCliente().getClienteNombre());
                oneRow.add(presupuesto.getPresupuestoTotal());
                tableData.add(oneRow);
        }
        tbl_bus_pre_pre.setModel(new DefaultTableModel (tableData, tableHeaders));
        
    }//GEN-LAST:event_btn_bus_preActionPerformed

    private void btn_pres_bus_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pres_bus_verActionPerformed
        int presupuestoPos = tbl_bus_pre_pre.getSelectedRow();
        String presNombre = tbl_bus_pre_pre.getValueAt(presupuestoPos,0).toString();
        String clienteNombre = tbl_bus_pre_pre.getValueAt(presupuestoPos,1).toString();
        
        OperarLineaPresMaterial opeLinMat = new OperarLineaPresMaterial();
        OperarLineaPresTrabajo opeLinTra = new OperarLineaPresTrabajo();
        OperarPresupuestos opePre = new OperarPresupuestos();
        OperarClientes opeCli = new OperarClientes();
        
        Cliente cliente = opeCli.buscarCliente(clienteNombre);
        int clienteId = cliente.getClienteId();
        Presupuesto presupuesto = opePre.buscarPresupuesto(clienteId, presNombre);
        
        Vector<String> tableHeaders = new Vector <String>();
        tableHeaders.add("Concepto");
        tableHeaders.add("Precio");
        tableHeaders.add("Cantidad");
        tableHeaders.add("Total");
        
        List <LineaPresMaterial> lineasMat = opeLinMat.buscarLinea(presupuesto);
        List <LineaPresTrabajo> lineasTra = opeLinTra.buscarLinea(presupuesto);
        Vector tableData = new Vector();

        for(Object o : lineasMat){
            LineaPresMaterial linea = (LineaPresMaterial) o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(linea.getConcepto());
            oneRow.add(linea.getPrecio());
            oneRow.add(linea.getCantidad());
            oneRow.add(linea.getSubtotal());
            tableData.add(oneRow);
        }

        for(Object o : lineasTra){
            LineaPresTrabajo linea = (LineaPresTrabajo) o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(linea.getConcepto());
            oneRow.add(linea.getPrecio());
            oneRow.add(linea.getCantidad());
            oneRow.add(linea.getTotalLinea());
            tableData.add(oneRow);

        }
           
        opePre.calcularTotal(presupuesto);
        double total=opePre.devolverTotal(presupuesto);
        tbl_bus_pre_det.setModel(new DefaultTableModel (tableData, tableHeaders));
        txt_tot.setText(String.valueOf(total));
        double iva = (21*total)/100;
        txt_iva.setText(String.valueOf(iva));
        txt_tot_iva.setText(String.valueOf(total+iva));
    }//GEN-LAST:event_btn_pres_bus_verActionPerformed

    private void btn_pre_bus_impActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pre_bus_impActionPerformed
        List<ReportePresupuesto> lista = new ArrayList<ReportePresupuesto>();
        int presupuestoPos = tbl_bus_pre_pre.getSelectedRow();
        String presNombre = tbl_bus_pre_pre.getValueAt(presupuestoPos,0).toString();
        String clienteNombre = tbl_bus_pre_pre.getValueAt(presupuestoPos,1).toString();
        
        OperarLineaPresMaterial opeLinMat = new OperarLineaPresMaterial();
        OperarLineaPresTrabajo opeLinTra = new OperarLineaPresTrabajo();
        OperarPresupuestos opePre = new OperarPresupuestos();
        OperarClientes opeCli = new OperarClientes();
        
        Cliente cliente = opeCli.buscarCliente(clienteNombre);
        int clienteId = cliente.getClienteId();
        Presupuesto presupuesto = opePre.buscarPresupuesto(clienteId, presNombre);
        
        ReportePresupuesto reporte1 = new ReportePresupuesto(presupuesto.getPresupuestoId(), presupuesto.getPresupuestoTrabajo(), cliente.getClienteNombre(), cliente.getDniCif(), cliente.getClienteDireccion(),cliente.getClienteTelefono());
        lista.add(reporte1); 
        
        List<LineaPresMaterial> lineasMat = opeLinMat.buscarLinea(presupuesto);
        for(Object o : lineasMat){
            LineaPresMaterial linea = (LineaPresMaterial) o;
            if(linea.getCantidad()!= 0){
                ReportePresupuesto reporte = new ReportePresupuesto(linea.getConcepto(),linea.getPrecio(), linea.getCantidad(), linea.getSubtotal());
                lista.add(reporte);  
            }
        }
       
        List<LineaPresTrabajo> lineasTra = opeLinTra.buscarLinea(presupuesto);
        for(Object o : lineasTra){
            LineaPresTrabajo linea = (LineaPresTrabajo) o;
            if(linea.getCantidad()!=0){
                ReportePresupuesto reporte = new ReportePresupuesto(linea.getConcepto(),linea.getPrecio(), linea.getCantidad(), linea.getTotalLinea());
                lista.add(reporte);
            }
        }
        
        double total;
        total = presupuesto.getPresupuestoTotal();
        double iva =  total*21/100;
        double totalIva = total + iva;
        ReportePresupuesto reporte2 = new ReportePresupuesto(total, iva, totalIva);
        lista.add(reporte2); 
        
        
        File file = new File("src\\Reportes\\ReportePresupuesto.jasper");
        
        
        if(file.exists()){
            try{
                JasperReport reporte = (JasperReport) JRLoader.loadObject(file);//(getClass().getResource("Reportes\\ReportePresupuesto.jasper"));;//JasperCompileManager.compileReport("src/Reportes/ReportePresupuesto.jrxml");
                JasperPrint  print = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(lista));
                JasperViewer view = new JasperViewer(print, false);
                view.setVisible(true);
                view.setTitle("Guardar Presupuesto:");
            }catch(JRException e){
                e.printStackTrace();
            }
        }else{
            File file2 = new File("ReportePresupuesto.jasper");
            try{
                JasperReport reporte = (JasperReport) JRLoader.loadObject(file2);//(getClass().getResource("Reportes\\ReportePresupuesto.jasper"));;//JasperCompileManager.compileReport("src/Reportes/ReportePresupuesto.jrxml");
                JasperPrint  print = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(lista));
                JasperViewer view = new JasperViewer(print, false);
                view.setVisible(true);
                view.setTitle("Guardar Presupuesto:");
            }catch(JRException e){
                e.printStackTrace();
            }
        }
        
      
    }//GEN-LAST:event_btn_pre_bus_impActionPerformed

    private void btn_pre_bus_brrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pre_bus_brrActionPerformed
        int presupuestoPos = tbl_bus_pre_pre.getSelectedRow();
        String presNombre = tbl_bus_pre_pre.getValueAt(presupuestoPos,0).toString();
        String clienteNombre = tbl_bus_pre_pre.getValueAt(presupuestoPos,1).toString();
        
        OperarLineaPresMaterial opeLinMat = new OperarLineaPresMaterial();
        OperarLineaPresTrabajo opeLinTra = new OperarLineaPresTrabajo();
        OperarPresupuestos opePre = new OperarPresupuestos();
        OperarClientes opeCli = new OperarClientes();
        
        Cliente cliente = opeCli.buscarCliente(clienteNombre);
        int clienteId = cliente.getClienteId();
        Presupuesto presupuesto = opePre.buscarPresupuesto(clienteId, presNombre);
        int presupuestoId = presupuesto.getPresupuestoId();
        
        opePre.borrarPresupuesto(presupuestoId);
    }//GEN-LAST:event_btn_pre_bus_brrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bus_pre;
    private javax.swing.JButton btn_pre_bus_brr;
    private javax.swing.JButton btn_pre_bus_imp;
    private javax.swing.JButton btn_pres_bus_ver;
    private javax.swing.JComboBox<String> cmb_pre_bus_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbl_bus_pre_det;
    private javax.swing.JTable tbl_bus_pre_pre;
    private javax.swing.JTextField txt_bus_pre_nom;
    private javax.swing.JTextPane txt_iva;
    private javax.swing.JTextPane txt_tot;
    private javax.swing.JTextPane txt_tot_iva;
    // End of variables declaration//GEN-END:variables
}
